      - name: Generate GPG key if missing
        if: steps.check_key.outputs.private_key_exists == 'false'
        run: |
          cat >gen-key-script <<EOF
          %no-protection
          Key-Type: RSA
          Key-Length: 2048
          Subkey-Type: RSA
          Subkey-Length: 2048
          Name-Real: GitHub Actions Bot
          Name-Email: actions@github.com
          Expire-Date: 0
          %commit
          EOF
          gpg --batch --generate-key gen-key-script

          gpg --armor --export-secret-keys > private.key
          gpg --armor --export > public.key

          echo "=== PUBLIC KEY ==="
          cat public.key
          echo "=== END PUBLIC KEY ==="

          echo "=== PRIVATE KEY ==="
          cat private.key
          echo "=== END PRIVATE KEY ==="
